Repository algosup/2023-2024-project-5-flutter-team-1, pull requests merged in 2024-06, with the labels that each got.

#8 Technical Specifications and Test Plan Update
  .github/ISSUE_TEMPLATE/bugReport.yml
  .github/ISSUE_TEMPLATE/pullRequest.yml
  .github/ISSUE_TEMPLATE/testCases.yml
  documents/functional_specifications/functionalspecifications.md
  documents/management/codeofconduct.md
  documents/management/managementdocument.md
  documents/management/projectcharter.md
  documents/management/weeklyreports.md
  documents/technical_specifications/technicalspecifications.md
  documents/test_plan/testplan.md
Labels: documentation, enhancement, critical

#24 Merging Documents
  documents/management/projectcharter.md
  documents/management/weeklyreports.md
  documents/technical_specifications/technicalspecifications.md
  documents/test_plan/testplan.md
  documents/user_manual/assets/AgreeEN.jpg
  documents/user_manual/assets/CompAccEN.png
  documents/user_manual/assets/CompInfEN.png
  documents/user_manual/assets/LangEN.png
  documents/user_manual/assets/MPIData.jpg
  documents/user_manual/assets/PDataEN.jpg
  documents/user_manual/assets/RegEN.jpg
  documents/user_manual/assets/SDataEN.jpg
  documents/user_manual/usermanual.md
  documents/user_manual/usermanual.pdf
Labels: documentation, critical

#26 Update README
  README.md
  documents/management/managementdocument.md
  documents/management/weeklyreports.md
Labels: documentation, enhancement, high

#27 Final update
  src/lib/pages/candidate/chatpage.dart
  src/lib/pages/candidate/homepage.dart
  src/lib/routes.dart
Labels: enhancement, critical, finished

#29 Major UI changes
  src/lib/pages/candidate/aboutpage.dart
  src/lib/pages/candidate/chatpage.dart
  src/lib/pages/candidate/helppage.dart
  src/lib/pages/candidate/languagepage.dart
  src/lib/pages/candidate/notificationspage.dart
  src/lib/pages/candidate/privacypage.dart
  src/lib/pages/candidate/securitypage.dart
  src/lib/pages/candidate/settingspage.dart
Labels: enhancement, finished, program
